import unittest
import re
from datetime import datetime, timedelta
import config
from pipeline import is_relevant_tender
from gem_scraper import GeMPortalScraper, get_authentic_bid_document_url
from sheets_manager import GoogleSheetsManager
from repair_sheet_links import is_naive_or_invalid_url

class TestTenderPipeline(unittest.TestCase):

    def setUp(self):
        self.scraper = GeMPortalScraper(headless=True)

    def test_gem_id_regex(self):
        sample_texts = [
            "We have requirement for cooling tower tender GEM/2026/B/1234567 please quote.",
            "Tender ID: GEM/2024/B/9876543 issued by BHEL",
            "Refer GeM bid GEM/2025/B/5544332 for cryogenic plant",
            "Invalid bid ID GEM/24/B/123 or ABC/1234/B/123"
        ]
        extracted = []
        for text in sample_texts:
            matches = re.findall(config.GEM_ID_REGEX, text, re.IGNORECASE)
            extracted.extend(matches)

        self.assertIn("GEM/2026/B/1234567", extracted)
        self.assertIn("GEM/2024/B/9876543", extracted)
        self.assertIn("GEM/2025/B/5544332", extracted)
        self.assertEqual(len(extracted), 3)

    def test_keyword_whitelist_filtering(self):
        """Tests that is_relevant_tender strictly accepts whitelisted keywords and rejects others."""
        # Relevant tenders
        self.assertTrue(is_relevant_tender("Supply of Cooling Tower System", "Induced draft FRP cooling tower"))
        self.assertTrue(is_relevant_tender("Cryogenic Storage Tanks", "Vacuum insulated cryogenic tanks"))
        self.assertTrue(is_relevant_tender("Medical Oxygen Generator", "Liquid Oxygen plant spares"))
        self.assertTrue(is_relevant_tender("Nitrogen Gas Plant", "PSA Nitrogen system"))
        self.assertTrue(is_relevant_tender("Industrial Gas Analyzer", "Infrared optical gas analyzer"))

        # Irrelevant tenders
        self.assertFalse(is_relevant_tender("Office Stationery Supply", "Paper, pens, and printer cartridges"))
        self.assertFalse(is_relevant_tender("Civil Construction Work", "Road repair and bituminous concrete"))
        self.assertFalse(is_relevant_tender("Desktop Computers & Laptops", "Intel Core i7 work stations"))
        self.assertFalse(is_relevant_tender("Water Purifier RO Plant", "Domestic RO water filtration"))

    def test_is_naive_or_invalid_url_detection(self):
        """Tests detection of string-constructed naive URLs vs authentic URLs."""
        gem_id = "GEM/2026/B/7941504"

        # Naive URLs generated by appending GeM ID digits
        self.assertTrue(is_naive_or_invalid_url("https://bidplus.gem.gov.in/showbidDocument/7941504", gem_id))
        self.assertTrue(is_naive_or_invalid_url("Not Found", gem_id))
        self.assertTrue(is_naive_or_invalid_url("", gem_id))

        # Authentic URLs with internal document IDs (do not equal the GeM bid number)
        self.assertFalse(is_naive_or_invalid_url("https://bidplus.gem.gov.in/showbidDocument/9839183", gem_id))
        self.assertFalse(is_naive_or_invalid_url("https://bidplus.gem.gov.in/buyer_documents/12345", gem_id))

    def test_dynamic_days_left_calculation(self):
        """Tests dynamic calculation of remaining days: (end_date - datetime.now()).days."""
        # Future date 10 days ahead
        future_date = datetime.now() + timedelta(days=10, hours=2)
        future_str = future_date.strftime("%d-%m-%Y %H:%M:%S")
        days_left = self.scraper._calculate_days_left(future_str)
        self.assertIsNotNone(days_left)
        self.assertEqual(days_left, 10)

        # Past date (expired)
        past_date = datetime.now() - timedelta(days=5)
        past_str = past_date.strftime("%d-%m-%Y")
        days_left_past = self.scraper._calculate_days_left(past_str)
        self.assertIsNotNone(days_left_past)
        self.assertTrue(days_left_past < 0)

    def test_extract_tender_description_multiline(self):
        """Tests that full item description is extracted without truncation and whitespace cleaned."""
        card_text = """
        Bid Details:
        Item(s): High Precision Oxygen Gas Analyzer with
        Dual Channel Sensor System and Digital Display Unit
        Quantity: 5
        Department Name And Address: Ministry of Defence, New Delhi
        Start Date: 01-09-2026 10:00 AM
        End Date: 20-09-2026 03:00 PM
        """
        desc = self.scraper._extract_tender_description(None, card_text)
        expected = "High Precision Oxygen Gas Analyzer with Dual Channel Sensor System and Digital Display Unit"
        self.assertEqual(desc, expected)

    def test_row_formatting_with_new_columns(self):
        """Tests Google Sheets row formatting with Start Date, Days Left, and alias compatibility."""
        sample_data = {
            "Scraped Date": "2026-08-27 15:30:00",
            "GeM ID": "GEM/2026/B/1234567",
            "Tender Description": "Cryogenic Oxygen Plant",
            "Buyer Name": "Ministry of Defence",
            "Start Date": "2026-08-20",
            "End Date to Participate": "2026-09-10",
            "Days Left": 14,
            "Tender Opening Date": "2026-09-11",
            "Work Completion Date": "180 Days",
            "Product Description": "Liquid Oxygen Plant",
            "Seller Category": "MSE Relaxed/Preferred",
            "Tender Value": "INR 1,20,00,000",
            "City": "Pune, Maharashtra",
            "Eligibility Criteria": "Turnover: 2 Cr; Experience: 5 Years",
            "Source URL": "https://bidplus.gem.gov.in/showbidDocument/9339177"
        }

        manager = GoogleSheetsManager.__new__(GoogleSheetsManager)
        row = manager._format_row(sample_data)

        self.assertEqual(len(row), len(config.SHEET_COLUMNS))
        self.assertEqual(row[0], "2026-08-27 15:30:00")
        self.assertEqual(row[1], "GEM/2026/B/1234567")
        self.assertEqual(row[2], "Cryogenic Oxygen Plant")
        self.assertEqual(row[4], "2026-08-20")  # Tender Release Date / Start Date (Col E)
        self.assertEqual(row[5], "2026-09-10 (14 Days Left)")  # End Date with Days Left embedded (Col F)
        self.assertEqual(row[10], "INR 1,20,00,000") # Tender Value (Col K)
        self.assertEqual(row[13], "https://bidplus.gem.gov.in/showbidDocument/9339177") # Tender URL (Col N)
        self.assertEqual(row[14], "marketing@cryocorp.co.in") # Assigned To (Col O)

        # Test formula stripping on Column N
        sample_data["Tender URL"] = '=HYPERLINK("https://bidplus.gem.gov.in/showbidDocument/9339177", "Link")'
        row_stripped = manager._format_row(sample_data)
        self.assertEqual(row_stripped[13], "https://bidplus.gem.gov.in/showbidDocument/9339177")

if __name__ == "__main__":
    unittest.main()
